# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
   exclude:
     - '*'
  tags:
    include:
      - '*'

jobs:
  - job: LinuxRelease
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
      - template: devtools/azure/linux-dependencies.yml
        parameters:
          rustup_toolchain: 'stable'
          node_version: '14.x'
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - script: |
          rm -rf packages/indexer/build
          yarn
          yarn workspace @ckb-lumos/indexer run package
        displayName: "Build release packages"
  - job: OSXRelease
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - template: devtools/azure/osx-dependencies.yml
        parameters:
          rustup_toolchain: 'stable'
          node_version: '14.x'
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - script: |
          rm -rf packages/indexer/build
          yarn
          yarn workspace @ckb-lumos/indexer run package
        displayName: "Build release packages"
  - job: WindowsRelease
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: devtools/azure/windows-dependencies.yml
        parameters:
          rustup_toolchain: 'stable'
          node_version: '14.x'
      - script: |
          npm -g install neon-cli
        displayName: "Install neon-cli"
      - script: |
          rm -rf packages/indexer/build
          yarn
          yarn workspace @ckb-lumos/indexer run package
        displayName: "Build release packages"
